name: ItemFilter
version: 0.1-B2
author: xwerswoodx
main: qlt.xwerswoodx.itemfilter.main
commands:
  ItemFilter:
    description: Opens filter menu.
    aliases: [if]

permissions:
  ItemFilter.admin:
    default: op
  ItemFilter.use:
    default: op
  ItemFilter.size2:
    default: op
  ItemFilter.size3:
    default: op
  ItemFilter.size4:
    default: op
  ItemFilter.size5:
    default: op
  ItemFilter.size6:
    default: op